sonar.projectKey=SocietyManagementSystem
sonar.working.directory=C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem
sonar.pullrequest.cache.basepath=C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem

4AD3C3FC-B74F-4604-BDBA-0D9251D8A8D6.sonar.projectKey=SocietyManagementSystem:4AD3C3FC-B74F-4604-BDBA-0D9251D8A8D6
4AD3C3FC-B74F-4604-BDBA-0D9251D8A8D6.sonar.projectName=SocietiesManagementSystem
4AD3C3FC-B74F-4604-BDBA-0D9251D8A8D6.sonar.projectBaseDir=C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem
4AD3C3FC-B74F-4604-BDBA-0D9251D8A8D6.sonar.sourceEncoding=utf-8
4AD3C3FC-B74F-4604-BDBA-0D9251D8A8D6.sonar.tests=
4AD3C3FC-B74F-4604-BDBA-0D9251D8A8D6.sonar.sources=\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Data\\DbHelper.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Form1.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Form1.Designer.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\AdminDashboardForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\ApproveEventsForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\AssignSocietyHeadForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\AssignTasksForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\LoginForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\ManageEventsForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\ManageMembershipsForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\ManageSocietiesForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\ManageSocietyProfileForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\ManageTicketsForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\ManageUsersForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\MonitorActivitiesForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\MyMembershipsForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\MyTicketsForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\RegisterForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\SocietyDashboardForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\SocietyForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\SocietyReportsForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\StudentDashboardForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\UniversityReportsForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Forms\\UpcomingEventsForm.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Models\\Event.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Models\\EventRegistration.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Models\\Membership.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Models\\Session.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Models\\Society.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Models\\SocietyTask.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Models\\User.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Program.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Services\\AuthService.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Services\\EventService.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Services\\MembershipService.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Services\\SocietyService.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Services\\TaskService.cs",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Report.md",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\Schema.sql",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\obj\\project.assets.json",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\obj\\SocietiesManagementSystem.csproj.nuget.dgspec.json",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\bin\\Debug\\net10.0-windows\\SocietiesManagementSystem.deps.json",\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\bin\\Debug\\net10.0-windows\\SocietiesManagementSystem.runtimeconfig.json"

4AD3C3FC-B74F-4604-BDBA-0D9251D8A8D6.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\.sonarqube\\out\\1"
4AD3C3FC-B74F-4604-BDBA-0D9251D8A8D6.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\.sonarqube\\out\\1\\Issues.json"
4AD3C3FC-B74F-4604-BDBA-0D9251D8A8D6.sonar.cs.scanner.telemetry=\
"C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\.sonarqube\\out\\1\\Telemetry.json"

4AD3C3FC-B74F-4604-BDBA-0D9251D8A8D6.sonar.working.directory=C:\\Users\\aawai\\OneDrive\\Desktop\\SocietiesManagementSystem\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=4AD3C3FC-B74F-4604-BDBA-0D9251D8A8D6

